datasource:
  test1:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://edgclearlove.top:3306/test?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
    username: dataViewer
    password: dataViewer
  test2:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://edgclearlove.top:3306/test2?characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=5
    username: dataViewer
    password: dataViewer
logging:
  level:
    com.lyle.sample.mybatis.mapper: debug